name: Build and Deploy of static site

on:
    push:
        branches: ["main"]

jobs:
    build_and_deploy_helios:
        name: Build and Deploy to Helios
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: setup Python and MkDocs
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install MkDocs dependencies
              run: pip install mkdocs

            - name: Build
              run: mkdocs build

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "./site"

            - name: Configure SSH and Private Key
              run: |
                  mkdir -p ~/.ssh
                  install -m 600 /dev/null ~/.ssh/id_rsa
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

            - name: Deploy to Helios via Pure Rsync
              run: |
                  rsync -ave "ssh -p 2222 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=yes" --delete ./site/ ${{ secrets.REMOTE_DEST }}

    deploy_pages:
        name: Deploy to GitHub Pages
        runs-on: ubuntu-latest
        needs: build_and_deploy_helios

        permissions:
            contents: read
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Deploy to Pages
              id: deployment
              uses: actions/deploy-pages@v4
