name: Build and Deploy of static site

on:
    push:
        branches: ["main"]

jobs:
    build_and_deploy_helios:
        name: Build and Deploy to Helios
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: setup Python and MkDocs
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install MkDocs dependencies
              run: pip install mkdocs

            - name: Build
              run: mkdocs build

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "./site"

            - name: Deploy MkDocs site to Helios via Rsync
              uses: burnett01/rsync-deployments@7.1.0
              with:
                  path: ./site/

                  remote_host: ${{ secrets.SERVER_HOST }}
                  remote_user: ${{ secrets.SERVER_USER }}
                  remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
                  remote_port: 2222

                  remote_path: public_html/

                  flags: -rtvz --delete

            - name: Log Helios Success Message
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: 2222
                  script: echo "Deployment to Helios finished successfully. Site available at https://se.ifmo.ru/~${{ secrets.SERVER_USER }}/"

    deploy_pages:
        name: Deploy to GitHub Pages
        runs-on: ubuntu-latest
        needs: build_and_deploy_helios

        permissions:
            contents: read
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Deploy to Pages
              id: deployment
              uses: actions/deploy-pages@v4
